version: '3.8'
services:
 myapp:
  build: .
  restart: always
  ports:
   - 3232:2323
  depends_on:
   - mongodb
   
 mongodb:
    image: mongo:6-jammy
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6:
  