server:
  port: 8098
spring:
  datasource:
    password: root-123
    url: jdbc:mysql://localhost:3306/mahabala
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
    show-sql: true

